name: CI Develop 🚀

on:
  pull_request:
    branches: [ develop ]
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    name: Tests & Coverage 🧪
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "ENV_STATE=test" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest tests \
            --cov=src \
            --cov-report=xml \
            --junitxml=test-results.xml

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            coverage.xml
            test-results.xml

  sonarless:
    name: Sonarless Analysis 📊
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download test reports
        uses: actions/download-artifact@v4
        with:
          name: test-reports

      - name: Run Sonarless
        uses: gitricko/sonarless@v1.3
        with:
          sonar-source-path: "."
          sonar-project-key: care-back
          sonar-project-name: Care Back
          sonar-metrics-path: sonar-metrics.json